sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

  before_deploy:
    -docker login -u <username> - <userpassword>
  
    deploy:
      provider: script
      script: docker push
